### ISSUE TITLE
lnst-ctl crashes when unreaan chable slavemachine is in a pool

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#188]
Version: c0c93a323c826017d970a551156d1294c1387152

Getting this traceback:

```
Traceback (most recent call last):
  File "./lnst-ctl", line 437, in <module>
    sys.exit(main())
  File "./lnst-ctl", line 413, in main
    reduce_sync, multi_match, pools)
  File "./lnst-ctl", line 166, in get_recipe_result
    restrict_pools=pools)
  File "/home/igyn/tmp/lnst/lnst/Controller/NetTestController.py", line 95, in __init__
    sp = SlavePool(pools, pool_checks)
  File "/home/igyn/tmp/lnst/lnst/Controller/SlavePool.py", line 53, in __init__
    self.add_dir(pool_name, pool_dir)
  File "/home/igyn/tmp/lnst/lnst/Controller/SlavePool.py", line 118, in add_dir
    s.shutdown(socket.SHUT_RDWR)
  File "/usr/lib64/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 107] Transport endpoint is not connected
```

The commit that introduced this bug is 5498ba20cd6e437ccc2413d0efd4fdbc8a8b4bd4.
A try/except block should fix this.

**Comment by jtluka** [comment]
Patch sent: https://lists.fedorahosted.org/archives/list/lnst-developers@lists.fedorahosted.org/thread/WSDCET4M66BJR2VW27H2THRLRFQMHIRB/
