### ISSUE TITLE
NetNamespace should override name property

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#202]
The `NetNamespace` class saves the netns name in `self._nsname`:
https://github.com/LNST-project/lnst/blob/32bca4040970e7a0b55373307a4e3857022f104a/lnst/Controller/NetNamespace.py#L29

However when new namespace is added, the `Host` property `name` is referenced that returns `self._name`:
https://github.com/LNST-project/lnst/blob/32bca4040970e7a0b55373307a4e3857022f104a/lnst/Controller/Host.py#L74

Since the NetNamespace does not have `_name`, None is returned and following traceback is printed:
```
Traceback (most recent call last):
  File "./test-gre.py", line 14, in <module>
    ctl.run(r)
  File "/root/lnst/lnst/Controller/Controller.py", line 160, in run
    recipe.test()
  File "/root/lnst/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 161, in test
    with self._test_wide_context() as main_config:
  File "/usr/lib64/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/root/lnst/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 168, in _test_wide_context
    config = self.test_wide_configuration()
  File "/root/lnst/lnst/Recipes/ENRT/BaseTunnelRecipe.py", line 62, in test_wide_configuration
    self.configure_underlying_network(configuration, [host1.eth0,host2.eth0])
  File "/root/lnst/lnst/Recipes/ENRT/Ip6GreNetnsTunnelRecipe.py", line 19, in configure_underlying_network
    m1.newns = NetNamespace("net1")
  File "/root/lnst/lnst/Controller/Namespace.py", line 196, in __setattr__
    if not self._custom_setattr(name, value):
  File "/root/lnst/lnst/Controller/Host.py", line 75, in _custom_setattr
    self._machine.add_netns(value.name)
  File "/root/lnst/lnst/Controller/Machine.py", line 585, in add_netns
    return self.rpc_call("add_namespace", netns)
  File "/root/lnst/lnst/Controller/Machine.py", line 235, in rpc_call
    netns = kwargs["netns"]
KeyError: 'netns'
```

**Comment by jtluka** [comment]
@olichtne there are two ways how to fix this. Should I simply override the the `name` property or rename the `_nsname` to `_name`?

**Comment by jtluka** [comment]
This is a minimal reproducer for the issue:
```
#!/usr/bin/python3

from lnst.Controller import Controller, BaseRecipe
from lnst.Controller.Requirements import HostReq, DeviceReq
from lnst.Devices import VethPair
from lnst.Controller.NetNamespace import NetNamespace

class NetnsRecipe(BaseRecipe):
    m1 = HostReq()
    m1.nic1 = DeviceReq('testnet')

    def test(self):
        m1 = self.matched.m1
        m1.veth0, m1.veth1 = VethPair()
        m1.run('ip l')
        m1.newns = NetNamespace("myns")
        m1.newns.run('ip l')
        m1.veth1.netns = m1.newns
        m1.newns.run('ip l')


        del m1.veth0

r = NetnsRecipe()

ctl = Controller(debug=True)
ctl.run(r)
```

**Comment by olichtne** [comment]
Looking at the git blame for the base `Namespace` class the commit da089a8c52bffc1edb155b4432d8f7e2847b2eee comes up and it renames `_nsname` to `name` so I think that's the proper fix for this issue.

**Comment by olichtne** [comment]
I experimented a little bit with that just to get it running, here's the patch I got, this is just to get it running on fedora28. The final solution should do a bit more testing than I have done with this. Either way pasting the patch here just in case it is useful:

```patch
diff --git a/lnst/Controller/Host.py b/lnst/Controller/Host.py
index a50a7ad1..f6c76b51 100644
--- a/lnst/Controller/Host.py
+++ b/lnst/Controller/Host.py
@@ -71,7 +71,7 @@ def map_device(self, dev_id, how):
     def _custom_setattr(self, name, value):
         if not super(Host, self)._custom_setattr(name, value):
             if isinstance(value, NetNamespace):
-                self._machine.add_netns(value.name)
+                self._machine.add_netns(value)
                 self._objects[name] = value
                 value._machine = self._machine
                 return True
diff --git a/lnst/Controller/Machine.py b/lnst/Controller/Machine.py
index 56d60cc5..58e09814 100644
--- a/lnst/Controller/Machine.py
+++ b/lnst/Controller/Machine.py
@@ -578,10 +578,10 @@ def __str__(self):
 
     def add_netns(self, netns):
         self._namespaces.append(netns)
-        return self.rpc_call("add_namespace", netns)
+        return self.rpc_call("add_namespace", netns.name)
 
     def del_netns(self, netns):
-        return self.rpc_call("del_namespace", netns)
+        return self.rpc_call("del_namespace", netns.name)
 
     def del_namespaces(self):
         for netns in self._namespaces:
@@ -598,4 +598,4 @@ def __getstate__(self):
         state['_msg_dispatcher'] = None
         if self.get_libvirt_domain():
             state['_domain_ctl'] = None
-        return state
\ No newline at end of file
+        return state
diff --git a/lnst/Controller/NetNamespace.py b/lnst/Controller/NetNamespace.py
index cb04b256..6c30d242 100644
--- a/lnst/Controller/NetNamespace.py
+++ b/lnst/Controller/NetNamespace.py
@@ -26,5 +26,5 @@ class NetNamespace(Namespace):
     def __init__(self, name):
         super(NetNamespace, self).__init__(None)
 
-        self._nsname = name
+        self._name = name
         #self.jobs = None #TODO
diff --git a/lnst/RecipeCommon/Perf/Measurements/NeperFlowMeasurement.py b/lnst/RecipeCommon/Perf/Measurements/NeperFlowMeasurement.py
index f271e1b3..d5cc0fa2 100644
--- a/lnst/RecipeCommon/Perf/Measurements/NeperFlowMeasurement.py
+++ b/lnst/RecipeCommon/Perf/Measurements/NeperFlowMeasurement.py
@@ -220,9 +220,9 @@ def get_interval(s_start: Dict, s_end: Dict, job_start: float,
     # unix time using job_start as reference
     timestamp = job_start + (s_start_time - neper_start)
     duration = s_end_time - s_start_time
-    cpu_usage = (utime_delta + stime_delta) / duration
+    cpu_usage = (utime_delta + stime_delta) / duration * 100
 
     interval = PerfInterval(transactions, duration, 'transactions', timestamp)
-    cpu_interval = PerfInterval(cpu_usage, duration, 'cpu_percent', timestamp)
+    cpu_interval = PerfInterval(cpu_usage * duration, duration, 'cpu_percent', timestamp)
 
     return interval, cpu_interval
```

**Comment by Kuba314** [comment]
I ran the reproducer just fine. This already seems fixed. See https://github.com/LNST-project/lnst/commit/8f5ed2de1e2e7708e715b4c89702f297d6970a9d (and maybe the surrounding commits).

I think this can be closed? @jtluka

**Comment by jtluka** [comment]
Thanks for checking, so let's close this. We have not seen any issues with that in the past few months.
