### ISSUE TITLE
cannot dump job description from exported recipe run data file

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#204]
Running following script fails with an exception.

```python
#!/usr/bin/python3

from lnst.Controller.Recipe import import_recipe_run

f = import_recipe_run('./lnst-run-data-0.lrc')

for r in f.results:
    print(r.__dict__)
    try:
        print(r._job.__dict__)
    except:
        pass
    print(r.description)
```

```
Calling Device method host1.host1-net1.vxlan_tunnel.ip_add(Ip6Address(6001:db8:ac10:fe01::2/64))
{'_timestamp': 1623850365.611658, '_success': True, '_job': <lnst.Controller.Job.Job object at 0x7fa1949d9c50>}
{'_what': 'ip -4 route add 192.168.7.0/24 dev t_vxlan0', '_expect': True, '_json': False, '_netns': None, '_desc': None, '_level': <ResultLevel.IMPORTANT: 1>, '_res': {'passed': True, 'res_data': {'stdout': '', 'stderr': ''}, 'type': 'result'}, '_id': 0}

Traceback (most recent call last):
  File "./read.py", line 13, in <module>
    print(r.description)
  File "/usr/lib/python3.6/site-packages/lnst-14_-py3.6.egg/lnst/Controller/RecipeResults.py", line 85, in description
    return "Job started: {}".format(str(self.job))
  File "/usr/lib/python3.6/site-packages/lnst-14_-py3.6.egg/lnst/Controller/Job.py", line 222, in __str__
    attrs.append("host(%s)" % self.host.hostid)
  File "/usr/lib/python3.6/site-packages/lnst-14_-py3.6.egg/lnst/Controller/Job.py", line 80, in host
    return self._netns.initns
AttributeError: 'NoneType' object has no attribute 'initns'
```

**Comment by jtluka** [comment]
Seems the netns is reset in [this method](https://github.com/LNST-project/lnst/blob/630c56993ccde6cd16d6762a4b697d2228af53e6/lnst/Controller/Job.py#L238) when pickling the RecipeRun object.
