### ISSUE TITLE
ValueError while running LNST in podman

### ISSUE THREAD

**Issue by Kuba314** [LNST-project/lnst#236]
In Podman, `ethtool.get_businfo()` throws an `IOError` with text `netlink error: Operation not supported`. This causes `_get_dev_interrupts` to fail with `ValueError`, because a regex constructed with empty output of `ethtool.get_businfo()` matches *every* line, which always matches the header of `/dev/interrupts`, which can't be parsed to an int.

There should probably be a check at `lnst/Recipes/ENRT/ConfigMixins/DevInterruptHWConfigMixin.py:123` if `dev.bus_info` failed. And then another one if stdout of the grep process is empty, because `int('')` also throws an error.

```
Traceback (most recent call last):
  File "/home/jake/rr/lnst/runner.py", line 25, in <module>
    main()
  File "/home/jake/rr/lnst/runner.py", line 14, in main
    ctl.run(SimpleNetworkRecipe(
  File "/home/jake/rr/lnst/lnst/Controller/Controller.py", line 173, in run
    recipe.test()
  File "/home/jake/rr/lnst/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 172, in test
    with self._sub_context(sub_config) as recipe_config:
  File "/usr/lib64/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/jake/rr/lnst/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 277, in _sub_context
    self.apply_sub_configuration(config)
  File "/home/jake/rr/lnst/lnst/Recipes/ENRT/ConfigMixins/BaseHWConfigMixin.py", line 6, in apply_sub_configuration
    self.hw_config(config)
  File "/home/jake/rr/lnst/lnst/Recipes/ENRT/ConfigMixins/PauseFramesHWConfigMixin.py", line 25, in hw_config
    super().hw_config(config)
  File "/home/jake/rr/lnst/lnst/Recipes/ENRT/ConfigMixins/ParallelStreamQDiscHWConfigMixin.py", line 24, in hw_config
    super().hw_config(config)
  File "/home/jake/rr/lnst/lnst/Recipes/ENRT/ConfigMixins/DevInterruptHWConfigMixin.py", line 52, in hw_config
    self._pin_dev_interrupts(dev, self.params.dev_intr_cpu)
  File "/home/jake/rr/lnst/lnst/Recipes/ENRT/ConfigMixins/DevInterruptHWConfigMixin.py", line 87, in _pin_dev_interrupts
    intrs = self._get_dev_interrupts(dev)
  File "/home/jake/rr/lnst/lnst/Recipes/ENRT/ConfigMixins/DevInterruptHWConfigMixin.py", line 135, in _get_dev_interrupts
    return [int(intr.strip()) for intr in res.stdout.strip().split('\n')]
  File "/home/jake/rr/lnst/lnst/Recipes/ENRT/ConfigMixins/DevInterruptHWConfigMixin.py", line 135, in <listcomp>
    return [int(intr.strip()) for intr in res.stdout.strip().split('\n')]
ValueError: invalid literal for int() with base 10: 'CPU0       CPU1       CPU2       CPU3       CPU4       CPU5       CPU6       CPU7'
```

**Comment by Kuba314** [comment]
At some point this error disappeared. Closing.
