### ISSUE TITLE
command with missing machine attribute gives message without any helpful info

### ISSUE THREAD

**Issue by jtluka** [LNST-project/lnst#28]
Recipe containing e.g.:

``` xml
<run command="echo hello-world"/>
```

Gives:

```
2013-09-11 04:03:40        (127.0.0.1)    DEBUG: 
    Traceback (most recent call last):
      File "/tmp/tmp.AaJu1pxRT2/lnst-ctl", line 73, in get_recipe_result
        packet_capture, log_ctl, pool_checks)
      File "/tmp/tmp.AaJu1pxRT2/lnst-ctl", line 55, in process_recipe
        pool_checks=pool_checks)
      File "/tmp/tmp.AaJu1pxRT2/lnst/Controller/NetTestController.py", line 69, in __init__
        self._recipe = parser.parse()
      File "/tmp/tmp.AaJu1pxRT2/lnst/Common/XmlParser.py", line 70, in parse
        raise exc
    XmlProcessingError: prefix-check.xml:37: Element run failed to validate attributes

2013-09-11 04:03:40        (127.0.0.1)    ERROR: prefix-check.xml:37: Element run failed to validate attributes
2013-09-11 04:03:40        (127.0.0.1)     INFO: ======================================== SUMMARY ========================================
2013-09-11 04:03:40        (127.0.0.1)     INFO:  prefix-check.xml                                                                   FAIL 
2013-09-11 04:03:40        (127.0.0.1)     INFO:      error message:prefix-check.xml:37: Element run failed to validate attributes  
2013-09-11 04:03:40        (127.0.0.1)     INFO: =========================================================================================
```

It would be great to see message like: "Command missing machine attribute ..."

**Comment by olichtne** [comment]
closing as not relevant anymore...
