### ISSUE TITLE
Exception after moving both veth peers into netns

### ISSUE THREAD

**Issue by SirPhuttel** [LNST-project/lnst#367]
Playing with multiple netns on a single host, discovered odd behaviour with
veth pairs. The code essentially is this:
```
host = self.matched.host

host.netns1 = NetNamespace("netns1")
host.netns2 = NetNamespace("netns2")
      
host.veth0, host.veth1 = VethPair()

host.netns1.veth0 = host.veth0
host.netns2.veth1 = host.veth1

host.netns1.veth0.up()
host.netns2.veth1.up()
```
The first up() method invocation causes an exception:
> 2024-05-08 17:02:36            (host)   netns1   ERROR:
>     Traceback (most recent call last):
>       File "/root/.cache/pypoetry/virtualenvs/lnst-MdZhQDa5-py3.12/lib/python3.12/site-packages/pyroute2/netlink/__init__.py", line 1719, in ft_encode
>         struct.pack_into(efmt, self.data, offset, value)
>     struct.error: argument for 's' must be a bytes object
> 
> 2024-05-08 17:02:36            (host)   netns1   ERROR: error pack: 0s 0 <class 'int'>

If I keep host.veth0 in init-ns, everything works fine. For reference, I attach the reproducer and debug logs. (Files with py suffix are not accepted, BTW.)

[veth_repro.py.txt](https://github.com/LNST-project/lnst/files/15251126/veth_repro.py.txt)
[lnst-debug.log](https://github.com/LNST-project/lnst/files/15251127/lnst-debug.log)

**Comment by jtluka** [comment]
I was able to reproduce the issue with container pool manager setup.

**Comment by jtluka** [comment]
@SirPhuttel are you running this with container pool manager? Also, what is the distro you use? This may be caused by newer Python version as we can see in the log, 3.12. I will check if this can be reproduced on a RHEL9 setup that we typically use.

**Comment by SirPhuttel** [comment]
@jtluka I reproduce this on F39. Container pool manager is not involved AFAICT, at least I have no idea what that is. :)

**Comment by jtluka** [comment]
I'm wondering why the device name in netlink message is `peer_lveth10`. This device is not anywhere in the log.
```
2024-05-08 17:02:36            (host)   netns1   DEBUG: 
    {'args': (),
     'kwargs': {'IFLA_IFNAME': 'lveth1',
                'IFLA_LINKINFO': {'attrs': [('IFLA_INFO_DATA',
                                             {'attrs': [('VETH_INFO_PEER',
                                                         {'attrs': [('IFLA_IFNAME',
                                                                     'peer_lveth10')]})]})]},
                'index': 115,
                'state': 'up'}}
```

**Comment by jtluka** [comment]
The problem seems to be only with the first device from the VethPair. The second device can be moved to the namespace and setting link up works without issues.

**Comment by jtluka** [comment]
Test run on RHEL-9.3 shows similar problem.
```
2024-05-09 08:40:44            (host)   netns1   DEBUG: Performing pyroute.IPRoute().link(set, *args, **kwargs)
2024-05-09 08:40:44            (host)   netns1   DEBUG:
    {'args': (),
     'kwargs': {'IFLA_IFNAME': 'lveth0',
                'IFLA_LINKINFO': {'attrs': [('IFLA_INFO_DATA',
                                             {'attrs': [('VETH_INFO_PEER',
                                                         {'attrs': [('IFLA_IFNAME',
                                                                     'peer_lveth00')]})]})]},
                'index': 11,
                'state': 'up'}}
2024-05-09 08:40:44            (host)   netns1   DEBUG:
    Traceback (most recent call last):
      File "/root/lnst_venv/bin/cache/12ee4eb9e41b1fbe254ce6a79e6a0528ddcc2e0561e720c901a1bee7999bf000", line 160, in _ipr_wrapper
        ret_val = obj(op_name, *args, **kwargs)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/iproute/linux.py", line 1619, in link
        ret = self.nlm_request(msg, msg_type=msg_type, msg_flags=msg_flags)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 822, in nlm_request
        return tuple(self._genlm_request(*argv, **kwarg))
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 1124, in nlm_request
        self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 389, in put
        self.sendto_gate(msg, addr)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/rtnl/iprsocket.py", line 49, in sendto_gate
        msg.encode()
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/rtnl/ifinfmsg/__init__.py", line 543, in encode
        return super(ifinfbase, self).encode()
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1245, in encode
        offset = self.encode_nlas(offset)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1566, in encode_nlas
        nla_instance.encode()
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1245, in encode
        offset = self.encode_nlas(offset)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1566, in encode_nlas
        nla_instance.encode()
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1242, in encode
        offset, diff = self.ft_encode(offset)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1708, in ft_encode
        length = len(value or '') + self.zstring
    TypeError: object of type 'type' has no len()

2024-05-09 08:40:44            (host)   netns1   DEBUG:
    Traceback (most recent call last):
      File "/root/lnst_venv/bin/cache/12ee4eb9e41b1fbe254ce6a79e6a0528ddcc2e0561e720c901a1bee7999bf000", line 160, in _ipr_wrapper
        ret_val = obj(op_name, *args, **kwargs)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/iproute/linux.py", line 1619, in link
        ret = self.nlm_request(msg, msg_type=msg_type, msg_flags=msg_flags)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 822, in nlm_request
        return tuple(self._genlm_request(*argv, **kwarg))
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 1124, in nlm_request
        self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/nlsocket.py", line 389, in put
        self.sendto_gate(msg, addr)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/rtnl/iprsocket.py", line 49, in sendto_gate
        msg.encode()
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/rtnl/ifinfmsg/__init__.py", line 543, in encode
        return super(ifinfbase, self).encode()
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1245, in encode
        offset = self.encode_nlas(offset)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1566, in encode_nlas
        nla_instance.encode()
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1245, in encode
        offset = self.encode_nlas(offset)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1566, in encode_nlas
        nla_instance.encode()
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1242, in encode
        offset, diff = self.ft_encode(offset)
      File "/root/lnst_venv/lib/python3.9/site-packages/pyroute2/netlink/__init__.py", line 1708, in ft_encode
        length = len(value or '') + self.zstring
    TypeError: object of type 'type' has no len()

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/root/lnst_venv/lib/python3.9/site-packages/lnst/Agent/Agent.py", line 1033, in _process_msg
        result = method(*args, **kwargs)
      File "/root/lnst_venv/lib/python3.9/site-packages/lnst/Agent/Agent.py", line 224, in dev_method
        return method(*args, **kwargs)
      File "/root/lnst_venv/bin/cache/12ee4eb9e41b1fbe254ce6a79e6a0528ddcc2e0561e720c901a1bee7999bf000", line 734, in up
        self._nl_link_sync("set")
      File "/root/lnst_venv/bin/cache/12ee4eb9e41b1fbe254ce6a79e6a0528ddcc2e0561e720c901a1bee7999bf000", line 145, in _nl_link_sync
        self._ipr_wrapper("link", op, index=self.ifindex, **attrs)
      File "/root/lnst_venv/bin/cache/12ee4eb9e41b1fbe254ce6a79e6a0528ddcc2e0561e720c901a1bee7999bf000", line 166, in _ipr_wrapper
        raise DeviceConfigError("Object {} operation {} on link {} failed: {}"
    lnst.Common.DeviceError.DeviceConfigError: Object link operation set on link lveth0 failed: object of type 'type' has no len()

2024-05-09 08:40:44       (localhost)        -    INFO: Result: FAIL, What: Calling Device method host.netns1.veth0.up()
2024-05-09 08:40:44       (localhost)        -   ERROR: Recipe execution terminated by unexpected exception
2024-05-09 08:40:44       (localhost)        -   DEBUG:
    Traceback (most recent call last):
      File "/root/lnst_venv/lib/python3.9/site-packages/lnst/Controller/Controller.py", line 172, in run
        recipe.test()
      File "/root/lnst_venv/lib/python3.9/site-packages/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 210, in test
        self.do_tests(recipe_config)
      File "/root/veth_repro.py", line 24, in do_tests
        host.netns1.veth0.up()
      File "/root/lnst_venv/lib/python3.9/site-packages/lnst/Devices/RemoteDevice.py", line 139, in dev_method
        return self._machine.remote_device_method(
      File "/root/lnst_venv/lib/python3.9/site-packages/lnst/Controller/Machine.py", line 165, in remote_device_method
        res = self.rpc_call("dev_method", index, method_name, args, kwargs,
      File "/root/lnst_venv/lib/python3.9/site-packages/lnst/Controller/Machine.py", line 320, in rpc_call
        return self._msg_dispatcher.send_message(self, msg)
      File "/root/lnst_venv/lib/python3.9/site-packages/lnst/Controller/MessageDispatcher.py", line 127, in send_message
        self._process_message(msg)
      File "/root/lnst_venv/lib/python3.9/site-packages/lnst/Controller/MessageDispatcher.py", line 224, in _process_message
        raise message[1]["Exception"]
    lnst.Common.DeviceError.DeviceConfigError: Object link operation set on link lveth0 failed: object of type 'type' has no len()
```

**Comment by jtluka** [comment]
> I'm wondering why the device name in netlink message is `peer_lveth10`. This device is not anywhere in the log.
> 
> ```
> 2024-05-08 17:02:36            (host)   netns1   DEBUG: 
>     {'args': (),
>      'kwargs': {'IFLA_IFNAME': 'lveth1',
>                 'IFLA_LINKINFO': {'attrs': [('IFLA_INFO_DATA',
>                                              {'attrs': [('VETH_INFO_PEER',
>                                                          {'attrs': [('IFLA_IFNAME',
>                                                                      'peer_lveth10')]})]})]},
>                 'index': 115,
>                 'state': 'up'}}
> ```

Tried to fix this with passing the peer name with following change, the exception still occurs:
```diff
diff --git a/lnst/Controller/Machine.py b/lnst/Controller/Machine.py
index 8dd7f4f6..3fabcaf0 100644
--- a/lnst/Controller/Machine.py
+++ b/lnst/Controller/Machine.py
@@ -135,6 +135,9 @@ class Machine(object):
         dev_args = dev._dev_args
         dev_kwargs = dev._dev_kwargs
 
+        if dev.peer_name:
+            dev_kwargs['peer_name'] = dev.peer_name
+
         self.rpc_call("remap_device",
                 dev.ifindex,
                 clsname=dev_clsname,

```

**Comment by jtluka** [comment]
@SirPhuttel please test with code from https://github.com/LNST-project/lnst/pull/368. Note that you will have to restart the lnst-agent.
